drop table if exists post_tags cascade;
drop table if exists post_images cascade;
drop table if exists likes cascade;
drop table if exists comments cascade;
drop table if exists tags cascade;
drop table if exists posts cascade;

-- POSTS
create table posts
(
    id             bigint generated by default as identity primary key,
    title          varchar(255) not null,
    text           text         not null,
    likes_count    integer      not null    default 0,
    comments_count integer      not null    default 0,
    created_at     timestamp with time zone default current_timestamp not null,
    updated_at     timestamp with time zone default current_timestamp not null
);

create index idx_posts_created_at
    on posts (created_at);

create index idx_posts_title
    on posts (title);

create index idx_posts_text
    on posts (text);


-- TAGS
create table tags
(
    id   bigint generated by default as identity primary key,
    name varchar(64) not null unique
);


-- POST -> TAGS (M:N)
create table post_tags
(
    post_id bigint not null,
    tag_id  bigint not null,
    primary key (post_id, tag_id),

    constraint fk_post_tags_post
        foreign key (post_id)
            references posts (id)
            on delete cascade,

    constraint fk_post_tags_tag
        foreign key (tag_id)
            references tags (id)
            on delete cascade
);

create index idx_post_tags_post
    on post_tags (post_id);

create index idx_post_tags_tag
    on post_tags (tag_id);


-- COMMENTS
create table comments
(
    id         bigint generated by default as identity primary key,
    post_id    bigint                                             not null,
    text       text                                               not null,
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null,

    constraint fk_comments_post
        foreign key (post_id)
            references posts (id)
            on delete cascade
);

create index idx_comments_post_id
    on comments (post_id);


-- LIKES
create table likes
(
    id         bigint generated by default as identity primary key,
    post_id    bigint                                             not null,
    created_at timestamp with time zone default current_timestamp not null,

    constraint fk_likes_post
        foreign key (post_id)
            references posts (id)
            on delete cascade
);

create index idx_likes_post_id
    on likes (post_id);


-- POST IMAGES
create table post_images
(
    post_id      bigint primary key,
    image        bytea                                              not null,
    content_type varchar(64)                                        not null,
    updated_at   timestamp with time zone default current_timestamp not null,

    constraint fk_post_images_post
        foreign key (post_id)
            references posts (id)
            on delete cascade
);